[package]
name = "headr"
version = "0.1.0"
edition = "2021"

[dependencies]
anstyle = "=1.0.3"
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
pretty_assertions = "1.4.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
